name: Releases
on: 
  push:
    branches: 
      - master
    tags:
    - '*'

jobs:
  build:
      name: build_release
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Gulp Bundle
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx gulp bundle
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ui-bundle.zip
          allowUpdates: true 
      
